### ISSUE TITLE
Getting error in production

### ISSUE THREAD

**Issue by zacksiri** [vigetlabs/redirector#9]
```
2015-04-17 09:35:02 +0000: Rack app error: #<ArgumentError: wrong number of arguments (0 for 1)>
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/core_ext/kernel/reporting.rb:82:in `capture'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/redirector-1.0.1/lib/redirector/middleware.rb:43:in `with_optional_silencing'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/redirector-1.0.1/lib/redirector/middleware.rb:36:in `matched_destination'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/redirector-1.0.1/lib/redirector/middleware.rb:32:in `redirect?'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/redirector-1.0.1/lib/redirector/middleware.rb:22:in `response'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/redirector-1.0.1/lib/redirector/middleware.rb:10:in `call'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/actionpack-4.1.9/lib/action_dispatch/middleware/static.rb:84:in `call'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/railties-4.1.9/lib/rails/engine.rb:514:in `call'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/railties-4.1.9/lib/rails/application.rb:144:in `call'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/configuration.rb:82:in `call'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/server.rb:507:in `handle_request'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `call'
/home/ubuntu/apps/connectica/shared/bundle/ruby/2.2.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `block in spawn_thread'

```

**Comment by zacksiri** [comment]
this only happens when we add 

```ruby
    config.redirector.include_query_in_source = true
    config.redirector.silence_sql_logs = true
```

to `config/application.rb`

**Comment by brianjlandau** [comment]
With Ruby 2.2.0 and Rails 4.1.9 (the environment you seem to be running in) I'm seeing passing specs: https://travis-ci.org/vigetlabs/redirector/jobs/59504214

Can you provide some more details about your setup? What do you have `ActiveRecord::Base.logger` set to?

**Comment by thomasgallagher** [comment]
Got a very similar error with:
ruby '2.2.1'
gem 'rails', '4.2.1'

Reproduced on OS X and Heroku.
WEBrick and Puma both produce the same results.
Everything works ok with RAILS_ENV=development

Removing config.redirector.silence_sql_logs = true from application.rb as a workaround for now.

Let me know if I can help debug.
